name: vidhan-site

services:
  site:
    container_name: vidhan-site
    image: ghcr.io/vidhanio/site:local
    build: .
    restart: always
    environment:
      IP: 0.0.0.0
      PORT: 8080
    ports:
      - 8080:8080

networks:
  default:
    name: vidhan-site
