name: Continuous Integration/Continuous Deployment

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    permissions:
      contents: read

    runs-on: ubuntu-latest

    container:
      image: rust:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Execute tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-fail-fast

  check:
    name: Check

    permissions:
      contents: read

    runs-on: ubuntu-latest

    container:
      image: rust:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install `clippy`
        run: rustup component add clippy

      - name: Check code
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings

  format:
    name: Format

    permissions:
      contents: read

    runs-on: ubuntu-latest

    container:
      image: rustlang/rust:nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build:
    name: Build

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    needs:
      - test
      - check
      - format

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/vidhanio/site
          tags: |
            type=ref,event=branch
            type=sha
          flavor: |
            latest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy

    environment:
      name: Production
      url: https://vidhan.io

    permissions: {}

    runs-on: ubuntu-latest
