name: Build and Deploy the Container to Google Cloud Run
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: ${{ github.event.repository.name }}
  REGION: us-east1

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code from the repository
        id: checkout
        uses: actions/checkout@v2.4.0

      - name: Set up the Google Cloud SDK
        id: setup-gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Register Google Cloud SDK as a Docker credential helper
        id: register-gcloud-docker
        run: gcloud auth configure-docker

      - name: Build the Docker image
        id: build-image
        run: docker build . -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Publish the Docker image
        id: publish-image
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up the Google Cloud SDK
        id: setup-gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy the container to Google Cloud Run
        id: deploy-container
        uses: google-github-actions/deploy-cloudrun@v0.3.0
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
          region: ${{ env.REGION }}

      - name: Show the Google Cloud Run URL
        run: echo ${{ steps.deploy.outputs.url }}
